import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { FITS } from '../../src/fits'
import { CompressedImage } from '../../src/fits/compressed-image'

function readFixture(path: string): ArrayBuffer {
  const bytes = readFileSync(path)
  return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength)
}

describe('standards fixtures: FITS compressed images', () => {
  const expected4x4 = [-30, -10, 0, 10, 20, 40, 80, 120, 160, 200, 240, 280, 320, 360, 400, 440]

  it('decodes HCOMPRESS_1 fixture generated by Astropy', async () => {
    const fits = FITS.fromArrayBuffer(
      readFixture('test/fixtures/standards/fits/hcompress_4x4_i16.fits'),
    )
    const hdu = fits.hdus[1]
    expect(hdu?.header.getString('ZCMPTYPE')).toBe('HCOMPRESS_1')
    expect(hdu?.data).toBeInstanceOf(CompressedImage)

    const frame = await (hdu!.data as CompressedImage).getFrame(0)
    expect(Array.from(frame)).toEqual(expected4x4)
  })

  it('decodes PLIO_1 fixture generated by Astropy', async () => {
    const fits = FITS.fromArrayBuffer(readFixture('test/fixtures/standards/fits/plio_4x4_i16.fits'))
    const hdu = fits.hdus[1]
    expect(hdu?.header.getString('ZCMPTYPE')).toBe('PLIO_1')
    expect(hdu?.data).toBeInstanceOf(CompressedImage)

    const frame = await (hdu!.data as CompressedImage).getFrame(0)
    expect(Array.from(frame)).toEqual([0, 0, 1, 1, 5, 5, 5, 10, 10, 20, 20, 30, 30, 30, 40, 40])
  })

  it('decodes GZIP_1 fixture generated by Astropy', async () => {
    const fits = FITS.fromArrayBuffer(readFixture('test/fixtures/standards/fits/gzip_4x4_i16.fits'))
    const hdu = fits.hdus[1]
    expect(hdu?.header.getString('ZCMPTYPE')).toBe('GZIP_1')
    expect(hdu?.data).toBeInstanceOf(CompressedImage)

    const frame = await (hdu!.data as CompressedImage).getFrame(0)
    expect(Array.from(frame)).toEqual(expected4x4)
  })

  it('decodes RICE_1 fixture generated by Astropy', async () => {
    const fits = FITS.fromArrayBuffer(readFixture('test/fixtures/standards/fits/rice_4x4_i16.fits'))
    const hdu = fits.hdus[1]
    expect(hdu?.header.getString('ZCMPTYPE')).toBe('RICE_1')
    expect(hdu?.data).toBeInstanceOf(CompressedImage)

    const frame = await (hdu!.data as CompressedImage).getFrame(0)
    expect(Array.from(frame)).toEqual(expected4x4)
  })

  it('reconstructs multi-tile GZIP_1 images with partial edge tiles', async () => {
    const fits = FITS.fromArrayBuffer(
      readFixture('test/fixtures/standards/fits/gzip_5x4_i16_tiled_3x2.fits'),
    )
    const hdu = fits.hdus[1]
    expect(hdu?.header.getString('ZCMPTYPE')).toBe('GZIP_1')
    expect(hdu?.header.getNumber('ZTILE1')).toBe(3)
    expect(hdu?.header.getNumber('ZTILE2')).toBe(2)
    expect(hdu?.data).toBeInstanceOf(CompressedImage)

    const frame = await (hdu!.data as CompressedImage).getFrame(0)
    expect(Array.from(frame)).toEqual([
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    ])
  })
})
